---
- name: "Install Snap on CentOS | Install | {{ _title_pfx }}"
  become: true
  block:
    - name: "Install EPEL repository | Install CentOS | Install | {{ _title_pfx }}"
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: "Refresh yum cache and update all packages | Install CentOS | Install | {{ _title_pfx }}"
      ansible.builtin.yum:
        name: "*"
        state: present
        update_cache: true

    - name: "Install snapd | Install CentOS | Install | {{ _title_pfx }}"
      ansible.builtin.yum:
        name: snapd
        state: present

    - name: "Start and enable snapd | Install CentOS | Install | {{ _title_pfx }}"
      ansible.builtin.systemd_service:
        name: snapd.socket
        state: started
        enabled: true

    - name: "Create symbolic link for classic snapd | Install CentOS | Install | {{ _title_pfx }}"
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
