---
- name: "Install Snap on Fedora | Install | {{ _title_pfx }}"
  become: true
  block:
    - name: "Install snapd | Install Fedora | Install | {{ _title_pfx }}"
      ansible.builtin.dnf:
        name: snapd
        state: present

    - name: "Start and enable snapd | Install Fedora | Install | {{ _title_pfx }}"
      ansible.builtin.systemd:
        name: snapd.socket
        state: started
        enabled: true

    - name: "Create symbolic link for classic snapd | Install Fedora | Install | {{ _title_pfx }}"
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
