---
- name: "Config Certbot | Config | {{ _title_pfx }}"
  become: true
  tags: [config, update]
  block:
    - name: "Header | Config | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "---------------------------------- CONFIG ----------------------------------"

    - name: "Check required parameters | Config | {{ _title_pfx }}"
      ansible.builtin.assert:
        that:
          - "{{ item }} | default('', true) | length > 0"
        fail_msg: "Required parameter '{{ item }}' is not defined."
        success_msg: "Required parameter '{{ item }}' is ok."
        quiet: true
      loop:
        - certbot__email
      when: not _registered.stat.exists

    - name: "Create required directories | Config | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: "{{ certbot__user }}"
        group: "{{ certbot__group }}"
      loop:
        - "{{ certbot__cert_path }}"
        - "{{ certbot__key_path }}"
        - "{{ certbot__chain_path }}"
        - "{{ certbot__fullchain_path }}"
        - "{{ certbot__archive_path }}"

    - name: "Change group of directory letsencrypt | Config | {{ _title_pfx }}"
      ansible.builtin.file:
        path: "/etc/letsencrypt/"
        mode: "0750"
        owner: "{{ certbot__user }}"
        group: "{{ certbot__group }}"

    - name: "Create config file | Config | {{ _title_pfx }}"
      ansible.builtin.template:
        src: cli.ini.j2
        dest: "/etc/letsencrypt/cli.ini"
        mode: "0600"
        owner: "{{ certbot__user }}"
        group: "{{ certbot__group }}"

    - name: "Install plugin dns provider | Config | {{ _title_pfx }}"
      when: certbot__dns_provider != "" and certbot__dns_provider != "standalone"
      block:
        - name: "Confirm plugin containment level | Config | {{ _title_pfx }}"
          ansible.builtin.command:
            cmd: "snap set certbot trust-plugin-with-root=ok"
          register: _plugin_containment_level
          changed_when: _plugin_containment_level.rc == 0

        - name: "Install plugin dns provider | Config | {{ _title_pfx }}"
          community.general.snap:
            name: certbot-dns-{{ certbot__dns_provider | default('dnsimple', true) }}
            channel: stable
            state: present

        - name: "Create credentials directory | Config | {{ _title_pfx }}"
          ansible.builtin.file:
            path: "{{ certbot__dir_credentials }}"
            state: directory
            mode: "0600"
            owner: "{{ certbot__user }}"
            group: "{{ certbot__group }}"

        - name: "Create credentials file | Config | {{ _title_pfx }}"
          ansible.builtin.template:
            src: dns_credentials.ini.j2
            dest: "{{ certbot__dir_credentials }}/{{ certbot__dns_provider | default('dnsimple', true) }}.ini"
            mode: "0600"
            owner: "{{ certbot__user }}"
            group: "{{ certbot__group }}"
