---
- name: "Config Certbot | Config | {{ _title_pfx }}"
  delegate_to: "{{ ansible_hostname | default('localhost', true) }}"
  become: true
  tags: [config, update]
  block:
    - name: "Header | Config | {{ _title_pfx }}"
      ansible.builtin.debug:
        msg: "---------------------------------- CONFIG ----------------------------------"

    - name: "Install plugin dns provider | Install | {{ _title_pfx }}"
      when: certbot__dns_provider is defined or certbot__dns_provider != ""
      block:
        - name: "Confirm plugin containment level | Install | {{ _title_pfx }}"
          ansible.builtin.command:
            cmd: "snap set certbot trust-plugin-with-root=ok"
          register: _plugin_containment_level
          changed_when: _plugin_containment_level.rc == 0

        - name: "Install plugin dns provider | Install | {{ _title_pfx }}"
          community.general.snap:
            name: certbot-dns-{{ certbot__dns_provider | default('dnsimple', true) }}
            channel: stable
            state: latest

        - name: "Create credentials directory | Install | {{ _title_pfx }}"
          ansible.builtin.file:
            path: "{{ certbot__dir_credentials }}"
            state: directory
            mode: "0600"
            owner: root
            group: root

        - name: "Create credentials file | Install | {{ _title_pfx }}"
          ansible.builtin.template:
            src: dns_credentials.ini.j2
            dest: "{{ certbot__dir_credentials }}/{{ certbot__dns_provider | default('dnsimple', true) }}.ini"
            mode: "0600"
            owner: root
            group: root
