---
- name: "Install certificate with Certbot | Deploy | {{ _title_pfx }}"
  delegate_to: "{{ ansible_hostname | default('localhost', true) }}"
  become: true
  tags: [never, deploy]
  block:
    - name: ""
